"""
Integration unit tests for Wikipedia Ecosystem tools within CLI:
- Redirect Generator (--no-redirects / default enabled)
- High-value Stub Generator (--create-stubs)
- Navbox & Template Doc Auditor (--audit-navboxes)
- Category Curator (--curate-categories)
"""

from pathlib import Path
import shutil
import tempfile
import unittest
from unittest.mock import MagicMock, patch

from wiki_translator.cli import WikiTranslatorCLI, main
from wiki_translator.redirect_generator import RedirectGenerator
from wiki_translator.stub_generator import StubGenerator
from wiki_translator.navbox_generator import NavboxGenerator
from wiki_translator.template_doc_auditor import TemplateDocAuditor
from wiki_translator.category_curator import CategoryCurator
from wiki_translator.wiki_client import WikiSection


class TestCLIEcosystemIntegration(unittest.TestCase):
    def setUp(self):
        self.tmp_dir = Path(tempfile.mkdtemp())

    def tearDown(self):
        shutil.rmtree(self.tmp_dir, ignore_errors=True)

    def test_cli_ecosystem_flags_parsing(self):
        """Tests that new CLI arguments are correctly parsed and passed to WikiTranslatorCLI."""
        with patch(
            "sys.argv",
            [
                "wiki_translator",
                "The Runner (2026 film)",
                "--create-stubs",
                "--audit-navboxes",
                "--curate-categories",
                "--generate-redirects",
            ],
        ):
            with patch("wiki_translator.cli.WikiTranslatorCLI") as mock_cli:
                main()
                mock_cli.assert_called_once()
                _, kwargs = mock_cli.call_args
                self.assertTrue(kwargs["create_stubs"])
                self.assertTrue(kwargs["audit_navboxes"])
                self.assertTrue(kwargs["curate_categories"])
                self.assertTrue(kwargs["enable_redirects"])
                # Verify defaults for new production modules
                self.assertTrue(kwargs["metric_first"])
                self.assertFalse(kwargs["enrich_archives"])
                self.assertFalse(kwargs["check_media"])
                self.assertFalse(kwargs["upload_media"])

    def test_cli_redirects_disabled_by_default(self):
        """Tests that redirects are NOT generated by default without --generate-redirects."""
        cli = WikiTranslatorCLI(
            output_dir=str(self.tmp_dir),
            enable_redirects=False,
            enable_map_links=False,
            enable_cache=False,
            enable_compression=False,
            enable_delta_skip=False,
            enable_auto_glossary=False,
        )

        section = WikiSection(
            index=1,
            title="Pengantar",
            level=2,
            header_raw="== Pengantar ==",
            content="The Runner adalah film cerita seru laga.",
            word_count=7,
            char_count=40,
            translated_content="The Runner adalah film cerita seru laga.",
        )

        cli._save_output("the_runner_2026", "The Runner (film 2026)", [section])
        redirect_dir = self.tmp_dir / "redirects"
        self.assertFalse(redirect_dir.exists())

    def test_cli_generate_redirects_flag_creates_redirects(self):
        """Tests that enable_redirects=True creates output/redirects/."""
        cli = WikiTranslatorCLI(
            output_dir=str(self.tmp_dir),
            enable_redirects=True,
            enable_map_links=False,
            enable_cache=False,
            enable_compression=False,
            enable_delta_skip=False,
            enable_auto_glossary=False,
        )

        section = WikiSection(
            index=1,
            title="Pengantar",
            level=2,
            header_raw="== Pengantar ==",
            content="The Runner adalah film cerita seru laga.",
            word_count=7,
            char_count=40,
            translated_content="The Runner adalah film cerita seru laga.",
        )

        cli._save_output("the_runner_2026", "The Runner (film 2026)", [section])
        redirect_dir = self.tmp_dir / "redirects"
        self.assertTrue(redirect_dir.exists())
        saved_files = list(redirect_dir.glob("*.wikitext"))
        self.assertTrue(len(saved_files) > 0)
    def test_cli_create_stubs_generates_files(self):
        """Tests that --create-stubs scans for {{ill}} and generates stubs into output/stubs/."""
        mock_stub_gen = MagicMock(spec=StubGenerator)
        mock_stub_gen.generate_stub.return_value = {
            "id_title": "Kevin Macdonald",
            "en_title": "Kevin Macdonald (director)",
            "wikitext": "'''Kevin Macdonald''' adalah sutradara Skotlandia.",
        }
        mock_stub_gen.save_stub.side_effect = lambda info, d: (Path(d) / "stubs" / f"{info['id_title']}.wikitext")

        cli = WikiTranslatorCLI(
            output_dir=str(self.tmp_dir),
            create_stubs=True,
            stub_generator=mock_stub_gen,
            enable_map_links=False,
            enable_cache=False,
            enable_compression=False,
            enable_delta_skip=False,
            enable_auto_glossary=False,
        )

        section = WikiSection(
            index=1,
            title="Produksi",
            level=2,
            header_raw="== Produksi ==",
            content="Disutradarai oleh {{ill|Kevin Macdonald|en|Kevin Macdonald (director)}}.",
            word_count=6,
            char_count=60,
            translated_content="Disutradarai oleh {{ill|Kevin Macdonald|en|Kevin Macdonald (director)}}.",
        )

        cli._save_output("film_uji", "Film Uji", [section])
        mock_stub_gen.generate_stub.assert_called_once()
        mock_stub_gen.save_stub.assert_called_once()

    def test_cli_audit_navboxes_and_docs_generates_files(self):
        """Tests that --audit-navboxes scans missing navboxes and creates templates & docs in output/templates/."""
        mock_navbox_gen = MagicMock(spec=NavboxGenerator)
        mock_navbox_gen.generate_navbox.return_value = {
            "template_name": "Christopher Nolan",
            "id_title": "Templat:Christopher Nolan",
            "wikitext": "{{Kotak navigasi|nama=Christopher Nolan}}",
            "already_exists": False,
        }
        mock_navbox_gen.save_navbox.side_effect = lambda info, d: (Path(d) / "templates" / f"{info['template_name']}.wikitext")

        mock_doc_auditor = MagicMock(spec=TemplateDocAuditor)
        mock_doc_auditor.audit_and_generate.return_value = {
            "template_name": "Christopher Nolan",
            "wikitext": "<!-- Dokumentasi -->",
        }
        mock_doc_auditor.save_doc.side_effect = lambda info, d: (Path(d) / "templates" / f"{info['template_name']}_doc.wikitext")

        cli = WikiTranslatorCLI(
            output_dir=str(self.tmp_dir),
            audit_navboxes=True,
            navbox_generator=mock_navbox_gen,
            template_doc_auditor=mock_doc_auditor,
            enable_map_links=False,
            enable_cache=False,
            enable_compression=False,
            enable_delta_skip=False,
            enable_auto_glossary=False,
        )

        section = WikiSection(
            index=1,
            title="Navigasi",
            level=2,
            header_raw="== Referensi ==\n{{Daftar rujukan}}",
            content="{{Christopher Nolan}}",
            word_count=2,
            char_count=25,
            translated_content="== Referensi ==\n{{Daftar rujukan}}\n\n{{Christopher Nolan}}",
        )

        cli._save_output("film_nolan", "Film Nolan", [section])
        mock_navbox_gen.generate_navbox.assert_called_once_with("Christopher Nolan", check_existence=True)
        mock_navbox_gen.save_navbox.assert_called_once()
        mock_doc_auditor.audit_and_generate.assert_called_once()
        mock_doc_auditor.save_doc.assert_called_once()

    def test_cli_curate_categories_audit(self):
        """Tests that --curate-categories evaluates categories per WP:PEDKAT."""
        mock_cat_curator = MagicMock(spec=CategoryCurator)
        mock_cat_curator.curate_category.return_value = {
            "category_name": "Kategori:Film laga",
            "article_count": 5,
            "is_safe_to_create": True,
            "found_articles": ["A", "B", "C", "D", "E"],
            "parent_categories": ["[[Kategori:Film menurut genre]]"],
            "reason": "Aman untuk dibuat",
        }

        cli = WikiTranslatorCLI(
            output_dir=str(self.tmp_dir),
            curate_categories=True,
            category_curator=mock_cat_curator,
            enable_map_links=False,
            enable_cache=False,
            enable_compression=False,
            enable_delta_skip=False,
            enable_auto_glossary=False,
        )

        section = WikiSection(
            index=1,
            title="Kategori",
            level=2,
            header_raw="",
            content="[[Kategori:Film laga]]",
            word_count=2,
            char_count=22,
            translated_content="[[Kategori:Film laga]]",
        )

        cli._save_output("film_aksi", "Film Aksi", [section])
        mock_cat_curator.curate_category.assert_called_once_with("Film laga")

    def test_cli_scan_red_links(self):
        cli = WikiTranslatorCLI(
            output_dir=str(self.tmp_dir),
            enable_map_links=False,
            enable_cache=False,
        )
        wikitext = (
            "Disutradarai oleh {{ill|Kevin Macdonald (sutradara)|en|Kevin Macdonald (director)}} "
            "dan diproduseri oleh {{ill|David Kosse|en|David Kosse}} bersama "
            "{{ill|Alfred Enoch|en|Alfred Enoch}}."
        )
        red_links = cli.scan_red_links(wikitext)
        self.assertEqual(len(red_links), 3)
        self.assertEqual(red_links[0]["id_title"], "Kevin Macdonald (sutradara)")
        self.assertEqual(red_links[0]["en_title"], "Kevin Macdonald (director)")
        self.assertEqual(red_links[1]["id_title"], "David Kosse")
        self.assertEqual(red_links[1]["en_title"], "David Kosse")
        self.assertEqual(red_links[2]["id_title"], "Alfred Enoch")
        self.assertEqual(red_links[2]["en_title"], "Alfred Enoch")

    def test_cli_interactive_red_link_selection(self):
        mock_stub_gen = MagicMock(spec=StubGenerator)
        mock_stub_gen.generate_stub.return_value = {
            "id_title": "David Kosse",
            "en_title": "David Kosse",
            "wikitext": "Stub",
        }
        mock_stub_gen.save_stub.return_value = self.tmp_dir / "stubs" / "David_Kosse.wikitext"

        cli = WikiTranslatorCLI(
            output_dir=str(self.tmp_dir),
            create_stubs=False,
            stub_generator=mock_stub_gen,
            enable_map_links=False,
            enable_cache=False,
        )
        wikitext = (
            "{{ill|Kevin Macdonald|en|Kevin Macdonald (director)}} dan "
            "{{ill|David Kosse|en|David Kosse}}."
        )
        # Select only #2 (David Kosse)
        with patch("builtins.input", return_value="2"):
            created = cli._process_red_links_and_stubs(wikitext, is_interactive=True)

        self.assertEqual(created, 1)
        mock_stub_gen.generate_stub.assert_called_once_with(
            en_title="David Kosse",
            id_title="David Kosse",
            topic=None,
        )

    def test_cli_interactive_red_link_selection_none(self):
        mock_stub_gen = MagicMock(spec=StubGenerator)
        cli = WikiTranslatorCLI(
            output_dir=str(self.tmp_dir),
            create_stubs=False,
            stub_generator=mock_stub_gen,
            enable_map_links=False,
            enable_cache=False,
        )
        wikitext = "{{ill|Kevin Macdonald|en|Kevin Macdonald (director)}}"
        with patch("builtins.input", return_value="none"):
            created = cli._process_red_links_and_stubs(wikitext, is_interactive=True)

        self.assertEqual(created, 0)
        mock_stub_gen.generate_stub.assert_not_called()

    def test_cli_summary_argument_passed(self):
        with patch(
            "sys.argv",
            [
                "wiki_translator",
                "The Runner",
                "-m",
                "merapikan teks dan rujukan",
            ],
        ):
            with patch("wiki_translator.cli.WikiTranslatorCLI") as mock_cli:
                main()
                mock_cli.assert_called_once()
                _, kwargs = mock_cli.call_args
                self.assertEqual(kwargs["summary"], "merapikan teks dan rujukan")
    def test_cli_new_production_flags_parsing(self):
        """Tests that --check-media, --upload-media, --enrich-archives, and --no-metric-first parse correctly."""
        with patch(
            "sys.argv",
            [
                "wiki_translator",
                "Sample Movie",
                "--check-media",
                "--upload-media",
                "--enrich-archives",
                "--no-metric-first",
            ],
        ):
            with patch("wiki_translator.cli.WikiTranslatorCLI") as mock_cli:
                main()
                mock_cli.assert_called_once()
                _, kwargs = mock_cli.call_args
                self.assertTrue(kwargs["check_media"])
                self.assertTrue(kwargs["upload_media"])
                self.assertTrue(kwargs["enrich_archives"])
                self.assertFalse(kwargs["metric_first"])

    def test_cli_batch_flag_execution(self):
        """Tests that --batch flag triggers default_batch_runner.run_batch_from_file."""
        with patch(
            "sys.argv",
            [
                "wiki_translator",
                "--batch",
                "articles_queue.txt",
            ],
        ):
            with patch("wiki_translator.cli.default_batch_runner.run_batch_from_file") as mock_batch:
                mock_report = MagicMock()
                mock_report.succeeded = 2
                mock_report.total_articles = 2
                mock_report.total_elapsed_seconds = 1.25
                mock_batch.return_value = mock_report
                with patch("wiki_translator.cli.WikiTranslatorCLI"):
                    main()
                    mock_batch.assert_called_once()
                    call_args = mock_batch.call_args
                    self.assertEqual(call_args.kwargs["queue_file_path"], "articles_queue.txt")

    def test_save_output_with_metric_first_and_enrich_archives(self):
        """Tests that _save_output runs metric_first, enrich_archives, and records shared memory."""
        from wiki_translator.wiki_client import WikiSection
        cli = WikiTranslatorCLI(
            output_dir=str(self.tmp_dir),
            enable_map_links=False,
            enable_typography_sanitizer=False,
            enable_slop_linter=False,
            enable_syntax_balancer=False,
            enable_template_mapper=False,
            metric_first=True,
            enrich_archives=True,
            check_media=True,
        )
        cli.custom_glossary = {"director": "sutradara"}

        section = WikiSection(
            index=0,
            title="Lead",
            level=1,
            header_raw="",
            content="Jaraknya 100 miles (160 km). {{cite web|url=https://example.com}}",
            word_count=10,
            char_count=60,
            translated_content="Jaraknya 100 miles (160 km). {{cite web|url=https://example.com}}",
        )

        with patch("wiki_translator.cli.default_reference_checker.enrich_citations_with_archives") as mock_enrich:
            mock_enrich.side_effect = lambda wt: wt.replace("{{cite web|url=https://example.com}}", "{{cite web|url=https://example.com|archive-url=https://web.archive.org/web/1/https://example.com}}")
            with patch("wiki_translator.cli.default_media_manager.audit_article_media") as mock_audit:
                mock_audit.return_value = []
                with patch("wiki_translator.cli.default_shared_memory.remember_term") as mock_remember:
                    outputs = cli._save_output(slug="sample", title="Sample", sections=[section])
                    self.assertTrue(outputs.wikitext.exists())
                    content = outputs.wikitext.read_text(encoding="utf-8")
                    self.assertIn("160 km (100 mil)", content)
                    self.assertIn("archive-url", content)
                    mock_remember.assert_called_with("director", "sutradara", topic=None)
                    mock_audit.assert_called_once()


if __name__ == "__main__":
    unittest.main()
